# Neural Networks & Naïve Bayes

In [2]:
import pandas as pd

import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler

from intro.templates_jupyter_notebooks.Q5_SVM import y_train_all




In [3]:
df_train = pd.read_csv('../train_insurance_one_hot.csv')
df_test = pd.read_csv('../test_insurance_one_hot.csv')
X_train_all_feat = df_train.drop(columns=['chargeGroup', 'id'], axis=1)
X_test_all_feat = df_test.drop(columns=['chargeGroup', 'id'], axis=1)
y_train = df_train['chargeGroup']
y_test = df_test['chargeGroup']

## a)

In [4]:

import numpy as np

mlp=MLPClassifier(
    hidden_layer_sizes=(5, 5, 5, 5, 5),
    activation='logistic',
    max_iter=2000,
    random_state=42,
)
#train
mlp.fit(X_train_all_feat, y_train)

#predict
y_pred=mlp.predict(X_test_all_feat)

# confusion_matrix   acc
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print("Confusion matrix (MLP baseline):")
print(cm)
print("\nAccuracy (MLP baseline):", acc)


# 7. estimate proba predict_proba
y_proba = mlp.predict_proba(X_test_all_feat)
print("\nProbability estimates for the first 5 test instances:")



print("\nPer-class mean probabilities (over test set):")
print(np.mean(y_proba, axis=0))

print("\nPer-class std of probabilities (over test set):")
print(np.std(y_proba, axis=0))

Confusion matrix (MLP baseline):
[[  0   0  33]
 [  0   0 131]
 [  0   0 104]]

Accuracy (MLP baseline): 0.3880597014925373

Probability estimates for the first 5 test instances:

Per-class mean probabilities (over test set):
[0.11901759 0.41097875 0.47000366]

Per-class std of probabilities (over test set):
[1.28012444e-14 3.55703976e-15 9.95773498e-15]


## b)

In [5]:
# 标准化特征
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_all_feat)
X_test_scaled  = scaler.transform(X_test_all_feat)

best_acc = -1.0
best_hidden = None
best_pred = None

hidden = 0
max_hidden = 50

while hidden < max_hidden:
    hidden += 1

    mlp = MLPClassifier(
        hidden_layer_sizes=hidden,
        activation="logistic",
        max_iter=2000,
        random_state=42
    )

    mlp.fit(X_train_scaled, y_train)
    y_pred = mlp.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)

    print(f"For hidden size = {hidden}, test accuracy = {acc}")

    if acc > best_acc:
        best_acc = acc
        best_hidden = hidden
        best_pred = y_pred

print("\n[Search finished]")
print("Best hidden size:", best_hidden)
print("Best test accuracy:", best_acc)

cm_best = confusion_matrix(y_test, best_pred)
print("\nConfusion matrix (best MLP, scaled, 1 hidden layer):")
print(cm_best)

For hidden size =  1, test accuracy = 0.8619
For hidden size =  2, test accuracy = 0.9888
For hidden size =  3, test accuracy = 0.9925
For hidden size =  4, test accuracy = 0.9888
For hidden size =  5, test accuracy = 0.9888
For hidden size =  6, test accuracy = 0.9925
For hidden size =  7, test accuracy = 0.9888
For hidden size =  8, test accuracy = 0.9925
For hidden size =  9, test accuracy = 0.9925
For hidden size = 10, test accuracy = 0.9888
For hidden size = 11, test accuracy = 0.9888
For hidden size = 12, test accuracy = 0.9888
For hidden size = 13, test accuracy = 0.9925
For hidden size = 14, test accuracy = 0.9888
For hidden size = 15, test accuracy = 0.9925
For hidden size = 16, test accuracy = 0.9925
For hidden size = 17, test accuracy = 0.9888
For hidden size = 18, test accuracy = 0.9963
For hidden size = 19, test accuracy = 0.9888
For hidden size = 20, test accuracy = 0.9963
For hidden size = 21, test accuracy = 0.9888
For hidden size = 22, test accuracy = 0.9925
For hidden

## c)

In [6]:
from sklearn.naive_bayes import GaussianNB

#GaussianNB
gnb_raw = GaussianNB()
gnb_raw.fit(X_train_all_feat, y_train)
y_pred_raw = gnb_raw.predict(X_test_all_feat)

acc_raw = accuracy_score(y_test, y_pred_raw)
cm_raw = confusion_matrix(y_test, y_pred_raw)

print("\n[GaussianNB on RAW (unscaled) features]")
print("Accuracy:", acc_raw)
print("Confusion matrix:")
print(cm_raw)

#scaled GaussianNB

gnb_scaled = GaussianNB()
gnb_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = gnb_scaled.predict(X_test_scaled)

acc_scaled = accuracy_score(y_test, y_pred_scaled)
cm_scaled = confusion_matrix(y_test, y_pred_scaled)

print("\n[GaussianNB on SCALED features]")
print("Accuracy:", acc_scaled)
print("Confusion matrix:")
print(cm_scaled)


[GaussianNB on RAW (unscaled) features]
Accuracy: 0.9888059701492538
Confusion matrix:
[[ 33   0   0]
 [  0 131   0]
 [  3   0 101]]

[GaussianNB on SCALED features]
Accuracy: 0.7276119402985075
Confusion matrix:
[[ 33   0   0]
 [  0 131   0]
 [  5  68  31]]
